### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Njord7** [suixin1424/crossfire-yolo-TensorRT#1]
![image](https://user-images.githubusercontent.com/77720077/230618420-03bee060-e5bd-4205-bccc-99de530b37ad.png)
这个怎么解决，查了半天也没查到

**Comment by suixin1424** [comment]
https://blog.csdn.net/ymxyld/article/details/124964319可以参考这篇

**Comment by suixin1424** [comment]
可以参考这个https://blog.csdn.net/ymxyld/article/details/124964319

**Comment by suixin1424** [comment]
我更新了cmakelists，你重新编译一下应该可以了

**Comment by Njord7** [comment]
![image](https://user-images.githubusercontent.com/77720077/230759756-866c5403-6be0-4d5a-9e39-a5ddd5e9d213.png)
这个位置还是飘红，CSND的方法也试了还是不行...

**Comment by suixin1424** [comment]
把rect变量的四个参数转成int类型
