### ISSUE TITLE
请问编译提示这个

### ISSUE THREAD

**Issue by a2231698193** [suixin1424/crossfire-yolo-TensorRT#15]
![QQ截图20230704211913](https://github.com/suixin1424/crossfire-yolo-TensorRT/assets/45615515/08bc5abf-6af5-44e9-a52a-219bec66ea82)

**Comment by a2231698193** [comment]
已解决鼠标移动用的什么驱动 或者 设备

**Comment by suixin1424** [comment]
系统函数
