### ISSUE TITLE
程序有个问题请您看下

### ISSUE THREAD

**Issue by a2231698193** [suixin1424/crossfire-yolo-TensorRT#17]
在运行的时候，玩除了CF这个游戏 玩的是cfhd ，会很卡很卡 基本就是幻灯片，游戏的fps只有个位数，请问这个是，AI全部抢走了么，怎么能限制程序的最高帧率呢

**Comment by a2231698193** [comment]
@suixin1424

**Comment by suixin1424** [comment]
这个是用来对抗鼠标轨迹检测的
