### ISSUE TITLE
有几个问题，希望作者能够帮忙优化一下～

### ISSUE THREAD

**Issue by 6SvpGyx** [suixin1424/crossfire-yolo-TensorRT#22]
1.如果面前有多个识别目标的话 鼠标会乱抖动无法锁定目标。
2.只有在1920 * 1080 的分辨率下才能正确运行。
3.鼠标X方向锁定平移的速度和轨迹可以优化一下吗.现在比较快和生硬。

**Comment by suixin1424** [comment]
已更新。对于鼠标移动，自行调整pid参数或降低游戏内鼠标灵敏度

**Comment by 6SvpGyx** [comment]
> 已更新。对于鼠标移动，自行调整pid参数或降低游戏内鼠标灵敏度

好的感谢🙏！！
针对 1.如果面前有多个识别目标的话 鼠标会乱抖动无法锁定目标。 也优化了吗

**Comment by suixin1424** [comment]
程序mouse.cpp中本身有目标追踪算法，如感觉效果不理想，可自行优化

**Comment by 6SvpGyx** [comment]
1
