### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Njord7** [suixin1424/crossfire-yolo-TensorRT#4]
![image](https://github.com/suixin1424/crossfire-yolo-TensorRT/assets/77720077/76ed9f30-a860-44aa-9ec5-9c5b62fd19be)
请问这个问题咋解决，自己搞了半天也没弄好

**Comment by suixin1424** [comment]
我更新了cmakelists，你重新编译一下

**Comment by Njord7** [comment]
![2023-05-21_231353](https://github.com/suixin1424/crossfire-yolo-TensorRT/assets/77720077/27bb6731-a6e0-489d-a482-046e0e572c0c)
报错更多了。。是我哪里搞做错吗？

**Comment by Njord7** [comment]
解决了，是我安装的opencv版本太低了
