### ISSUE TITLE
游戏中如何侦测到键鼠事件

### ISSUE THREAD

**Issue by Telly-S** [suixin1424/crossfire-yolo-TensorRT#5]
现在穿越火线对后台侦测的拦截挺厉害的吧。

> #define KEY_DOWN(VK_NONAME) ((GetAsyncKeyState(VK_NONAME) & 0x8000) ? 1:0)

这种方式我试了，在游戏中是无法监听到键鼠事件的，不知道作者是用的什么方法呢？

**Comment by suixin1424** [comment]
以管理员身份运行

**Comment by Telly-S** [comment]
我刚试了一下，确实是这样，用管理员就可以侦测到了。
但是模拟按键时，是不是只能使用鼠标按键呢，像这样

>   mouse_event(MOUSEEVENTF_WHEEL, 0, 0, -120, 0); //鼠标滚轮下滚

但是键盘按键是不可以的

>   keybd_event(key_q, 0, 0, 0);  //按下
>  Sleep(150);
>  keybd_event(key_q, 0, KEYEVENTF_KEYUP, 0);  //弹起

作者有什么好方法吗，谢谢啦

**Comment by suixin1424** [comment]
键盘是可以的，参考我代码中config.cpp的41行

**Comment by Telly-S** [comment]
已经解决了，发现使用 `SendInput()` 方法是可以的，感谢。
