### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by Njord7** [suixin1424/crossfire-yolo-TensorRT#7]
![image](https://github.com/suixin1424/crossfire-yolo-TensorRT/assets/77720077/aa34fb5e-98a7-418d-ad99-e5c22353d414)
方便参考一下CMakeLists吗，我咋编译一直报错呢

**Comment by suixin1424** [comment]
新版本是不用cmake编译的，具体看tensorrt_pro

**Comment by Njord7** [comment]
好的，谢谢

**Comment by basikul** [comment]
您好，我是一名小白，可以教一下吗

**Comment by basikul** [comment]
> 好的，谢谢



> ![图像](https://user-images.githubusercontent.com/77720077/243105105-aa34fb5e-98a7-418d-ad99-e5c22353d414.png)方便参考一下CMakeLists吗，我咋编译一直报错呢

您好，我是一名小白，可以教一下吗
