### ISSUE TITLE
游戏帧数问题

### ISSUE THREAD

**Issue by Njord7** [suixin1424/crossfire-yolo-TensorRT#8]
再玩cfhd时，打开AI，游戏帧数很低，显卡占用上不去，但是切到别的窗口，显卡占用就上去了，游戏帧数也正常了，这是咋回事？
![image](https://github.com/suixin1424/crossfire-yolo-TensorRT/assets/77720077/05e3d4fc-ae47-4a2d-b256-aa772302f3d7)
![image](https://github.com/suixin1424/crossfire-yolo-TensorRT/assets/77720077/5617cb48-2a9c-445b-9ee3-fc48fc3519b0)

**Comment by suixin1424** [comment]
这个不清楚，游戏的问题吧，我玩的是cf，不是cfhd，没有这样的问题

**Comment by suixin1424** [comment]
或者你把模型精度从fp16改为int8

**Comment by Njord7** [comment]
我cf也正常，可能是游戏问题吧
